version: '2.0'
services:
  registry:
    image: registry:2.7
    restart: always
    ports:
      - 5000:5000
    volumes:
      - ./config.yml:/etc/docker/registry/config.yml

  ui:
    image: joxit/docker-registry-ui:static
    restart: always
    ports:
      - 8080:80
    environment:
      - REGISTRY_TITLE=NAP Lab Private Registry
      - URL=http://10.1.20.12:5000
    depends_on:
      - registry

