---
- hosts: centos
  become: true

  tasks:
  
  - name: Copy file with owner and permissions
    copy:
      src: nginx.conf
      dest: /etc/nginx/nginx.conf
      owner: gitlab-runner
      group: gitlab-runner

  - name: restart nginx
    service:
      name: nginx
      state: restarted
    become: yes