apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress-prometheus
  namespace: nginx-ingress
spec:
  externalTrafficPolicy: Local
  ports:
  - name: prometheus
    nodePort: 30113
    port: 9113
    protocol: TCP
    targetPort: 9113
  selector:
    app: nginx-ingress-nginx-ingress
  sessionAffinity: None
  type: NodePort